---
title: "STAT 631 Homework 2"
author: "Jack Cunningham (jgavc@tamu.edu)"
date: 09/09/2024
date-format: short
format:
  pdf:
    include-in-header:
      - text: |
          \usepackage{amsmath}
editor: visual
engine: knitr
---

## 

1\)

We have function $f^\star(y|\xi)$ below:

$$
f^\star(y|\xi)=\begin{cases} f(y\xi) & y<0 \\ f(y/\xi) & y \geq0\end{cases}
$$

We are tasked with integrating $f^{\star}(y|\xi)$:

$$
\int_{-\infty}^{\infty}f^\star(y|\xi)=\int_{-\infty}^0f(y\xi)dy+\int_0^\infty f(y/\xi)dy
$$

Let $u=y\xi$ so $du=\xi dy$. Let $w=y/\xi$ so $dw=\frac{1}{\xi}dy$. Then we have:

$$
\xi\int_{-\infty}^0f(u)du+\xi^{-1}\int_{0}^{\infty}f(w)dw
$$

$$
\xi(F(0)-F(-\infty))+\xi^{-1}(F(\infty)-F(0))
$$

Since $f$ is a symmetric pdf about 0 $F(0)=P(y<0)=1/2$. Also $F(-\infty)=0$ and $F(\infty)=1$ from basic rules about CDFs. Then we have our desired result:

$$
\xi(1/2-0)+\xi^{-1}(1-1/2)=\frac{1}{2}(\xi+\xi^{-1})
$$

2\)

a\)

The formula of Kurtosis for a random variable with a finite fourth moment is its fourth standardized moment.

$$
Kur=\frac{E[(x-\mu)^4]}{\sigma^4}
$$

We know that $Kur=3$ for a normal distribution. This implies that $E[(x-\mu)^4]=3\sigma^4$ for the normal distribution.

We have the below discrete density mixture:

$$
f(x)=.95f_1(x)+.05f_2(x)
$$

Where $f_1(x)$ is the density function of $N(0,1)$ and $f_2(x)=N(0,10)$.

A helpful fact for this problem is that $\mu^{(k)}=\sum_{i=1}^np_iE_{f_i}[x_i^{k}]$.Essentially when we are computing a moment we can compute each distributions's moment, multiply them by their weight, and sum them together.

This leads to $f(x)$ having $\sigma^2=p_1\sigma_1^2+p_2\sigma_2^2=.9(1)+.1(10)=1.9$. And $E[(x-\mu)^4]=p_1E_{f_1}[(x-\mu_1)^4]+p_2Ef_2[(x-\mu_2)^4]$. So using what we know about the fourth central moment of the normal distribution we have:

$$
E[(x-\mu)^4]=p_1(3\sigma_1^4)+p_2(3\sigma_2^4)
$$

Then we can compute kurtosis with the below:

$$
Kur=\frac{3(p_1\sigma_1^4+p_2\sigma_2^4)}{(p_1\sigma_1^2+p_2\sigma_2^2)^2}
$$

```{r}
p_1 <- .9
sigma_1 <- 1
p_2 <- .1
sigma_2 <- sqrt(10)

Kur <- 3*(p_1*sigma_1^4+p_2*sigma_2^4)/(p_1*sigma_1^2+p_2*sigma_2^2)^2
Kur
```

The kurtosis for this discrete mixture distribution is `r round(Kur,3)`.

b\)

Building off what I worked on in the previous question we have the below after substituting $\sigma_1=1,\sigma_2=\sigma,p_1=p,p_2=(1-p_1)$.

$$
Kur(p,\sigma)=\frac{3(p+(1-p)\sigma^4)}{(p+(1-p)\sigma^2)^2}
$$
